# permissions for end users to edit wenbingcustoms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wenbingcustom-editor-role
rules:
- apiGroups:
  - example.wenbing.org.wenbing
  resources:
  - wenbingcustoms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.wenbing.org.wenbing
  resources:
  - wenbingcustoms/status
  verbs:
  - get
